### ISSUE TITLE
Question: how to set micro as the default editor, after installing the flatpak of it?

### ISSUE THREAD

**Issue by MLSci** [flathub/io.github.zyedidia.micro#10]
Should I use `set -gx EDITOR`, `export EDITOR`, or .. ?

Also, I don't see the `~/.config/micro` folder. Is it supposed to be automatically created by the installation, or manually added by user?

**Comment by blt-r** [comment]
This was answered in https://github.com/zyedidia/micro/issues/2546#issuecomment-2067598866
