### ISSUE TITLE
Large package size

### ISSUE THREAD

**Issue by Nova-Aurora** [flathub/io.github.zyedidia.micro#3]
It appears that the flatpak runtime used is org.freedesktop.Sdk, which includes all development dependencies. This results in a large bundle size being shipped to the user (pictured here).
![image](https://github.com/flathub/io.github.zyedidia.micro/assets/62871042/4892c623-0896-48bd-93c6-3296f6035a8f)
The solution would be to swap runtimes to org.freedesktop.Platform.

**Comment by blt-r** [comment]
Yeah you're right. Micro doesn't really have much integration with the development environment, so using the Sdk is probably overkill
