### ISSUE TITLE
2.0.13 in Flathub?

### ISSUE THREAD

**Issue by MichaelTunnell** [flathub/io.github.zyedidia.micro#8]
I see that this repo was updated to 2.0.13 but 2.0.11 is the version on the Flathub. How do we update this in Flathub?

**Comment by blt-r** [comment]
I see. I set github to notify me on new releases of micro, but it just didn't (?). I'll update it now

**Comment by blt-r** [comment]
Or wait no, what. The repo is on 2.0.13. You can verify with `flatpak run io.github.zyedidia.micro --version`. You don't see it in your software store (or flathub website) because a new entry in the appdata file wasn't added. That file is upstream.
